tinyMCE.addI18n('es.advlink_dlg',{
title:"Insertar/editar hiperv\u00ednculo",
url:"URL del hiperv\u00ednculo",
target:"Destino",
titlefield:"T\u00tulo",
is_email:"La URL que ha introducido parece ser una direci\u00f3n de correo,  \u00bfdesea agregar el prefijo mailto: necesario?",
is_external:"La URL que ha introducido parece ser un v\u00ednculo externo,  \u00bfdesea agregar el prefijo http:// necesario?",
list:"Lista de v\u00ednculos",
general_tab:"General",
popup_tab:"Ventana",
events_tab:"Eventos",
advanced_tab:"Avanzados",
general_props:"Propiedades generales",
popup_props:"Propiedades de ventanas emergentes",
event_props:"Eventos",
advanced_props:"Propiedades avanzadas",
popup_opts:"Opciones",
anchor_names:"Anclas",
target_same:"Abrir en esta ventana / marco",
target_blank:"Abrir en ventana nueva",
target_top:"Abrir en el marco superior (reemplaza todos los marcos)",
target_parent:"Abrir en ventana padre / marco",
popup:"Javascript popup",
popup_url:"URL de la ventana emergente",
popup_name:"Nombre de la ventana",
popup_return:"Insertar \'return false\'",
popup_scrollbars:"Barras de desplazamiento",
popup_statusbar:"Barra de estado",
popup_toolbar:"Barra de herramientas",
popup_menubar:"Barra de men\u00fa",
popup_location:"Barra de localizaci\u00f3n",
popup_resizable:"Permitir cambiar el tama\u00f1o de la ventana",
popup_dependent:"Dependientes (s\u00f3lo Mozilla/Firefox)",
popup_size:"Tama\u00f1o",
width:"Ancho",
height:"Alto",
popup_position:"Posici\u00f3n (X/Y)",
id:"Id",
style:"Estilo",
classes:"Clases",
target_name:"Nombre del Target",
langdir:"Direcci\u00f3n del lenguaje",
target_langcode:"Lenguaje del Target",
langcode:"C\u00f3digo del lenguaje",
encoding:"Codificaci\u00f3n de caracteres del Target",
mime:"Tipo MIME del Target",
rel:"Relaci\u00f3n p\u00e1gina a target",
rev:"Relaci\u00f3n target a p\u00e1gina",
tabindex:"Indice de tabulaci\u00f3n",
accesskey:"Tecla de acceso",
ltr:"Izquierda a derecha",
rtl:"Derecha a izquierda",
link_list:"Lista de v\u00ednculo"
});
