<?php

function mobile_perm() {
  return array('administer mobile redirect');
} 

function mobile_menu(){
	$items['admin/settings/mobile-redirect'] = array(
		'title' => 'Redirección para móvil',
		'description' => t('Redirección para móvil'),		
		'page callback' => 'drupal_get_form', // assuming that you want to use a form
		'page arguments' => array('_mobile_form_builder'),
		'access callback' => 'user_access',
		'access arguments' => array('administer mobile redirect'), // or use hook_perm() to make your own
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

function _mobile_form_builder(){
	$form['redirect_url'] = array(
		'#type' => 'textfield',
		'#title' => t('Redirigir a...'),
		'#default_value' => variable_get('redirect_url', 'http://m.tantacom.com/presentacion') //false by default
	);
 
	// saves and executes a submission callback, see $form["#submit"] for that
	$form['save'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
        '#executes_submit_callback' => true
		
	);

    $form['#submit'] = array(
		'_mobile_form_submit_special_fuction_name'
	);
 
	return $form;
}

function _mobile_form_submit_special_fuction_name($form, &$form_state){
	//check $form_state['values'] and use this below line to set the value
	variable_set('redirect_url', $form_state['values']['redirect_url']);	
}

function is_mobile()
{
    module_load_include('php', 'mobile', 'Mobile_Detect');
    $detect = new Mobile_Detect();
    return $detect->isMobile();
}
